# Generated by Django 3.1.1 on 2020-10-30 14:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_blogposts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogposts',
            name='img',
        ),
        migrations.AddField(
            model_name='blogposts',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogposts',
            name='author',
            field=models.CharField(max_length=100),
        ),
    ]
